### ISSUE TITLE
how to fix that proplem

### ISSUE THREAD

**Issue by Jamsali** [jneilliii/OctoPrint-WemoSwitch#59]
Traceback (most recent call last):
  File "/home/hacker/Desktop/osi.ig/main.py", line 16, in <module>
    user_info(usrname=args["user"])
  File "/home/hacker/Desktop/osi.ig/.lib/api.py", line 70, in user_info
    js = json.loads(resp_js)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jneilliii** [comment]
Hard to tell without the full context of the log, but that appears to be an issue with getting data back from your device?
